// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace AraWeb.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240827161208_BogusGenerated")]
    partial class BogusGenerated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Apartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ApartmentId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BedsCount")
                        .HasColumnType("int");

                    b.Property<double>("CapacitySquare")
                        .HasColumnType("float");

                    b.Property<int>("GuestsCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<long>("ReviewsCount")
                        .HasColumnType("bigint");

                    b.Property<int>("RoomsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a67d595-7755-442a-9a42-37f2640813d8"),
                            Address = "138 Volkman Rue, Lake Christop, Guatemala",
                            BedsCount = 4,
                            CapacitySquare = 33.203785895073821,
                            GuestsCount = 6,
                            Name = "ꨘʺ㒅陖蟑崤ꌨ⚡㼃ꐭ",
                            OwnerId = new Guid("89f2b834-6d07-488b-bb97-e9debebb6f86"),
                            Rate = 0.41445252582852798,
                            ReviewsCount = 136837581L,
                            RoomsCount = 3
                        },
                        new
                        {
                            Id = new Guid("2aa5c6d0-1ca1-4c31-8c8f-0421c7790c20"),
                            Address = "452 Tony Lodge, Johnsonside, Honduras",
                            BedsCount = 5,
                            CapacitySquare = 36.855637839569241,
                            GuestsCount = 9,
                            Name = "徟ⓐ燡檔㐠ﮊᗍ矹Ʝ",
                            OwnerId = new Guid("89f2b834-6d07-488b-bb97-e9debebb6f86"),
                            Rate = 0.2198523486543863,
                            ReviewsCount = 1975188694L,
                            RoomsCount = 3
                        },
                        new
                        {
                            Id = new Guid("a2620e00-2a9e-402a-82be-179643c1f9d8"),
                            Address = "413 Lueilwitz Groves, East Adahton, Oman",
                            BedsCount = 6,
                            CapacitySquare = 89.947147117267562,
                            GuestsCount = 5,
                            Name = "擈ꮅ憾햁˪⢚ᮮ뷕",
                            OwnerId = new Guid("2d467980-ff3d-4572-b126-26bccb2f31e8"),
                            Rate = 0.40746795922977352,
                            ReviewsCount = 600323978L,
                            RoomsCount = 2
                        },
                        new
                        {
                            Id = new Guid("15d98c54-40d2-4573-9d26-e56a0053d8ca"),
                            Address = "16149 Emmett Skyway, Wunschfurt, Cayman Islands",
                            BedsCount = 6,
                            CapacitySquare = 81.325115686313836,
                            GuestsCount = 1,
                            Name = "㐖Ꚕ됦厯믿廽⵿虜灓䁄",
                            OwnerId = new Guid("2d467980-ff3d-4572-b126-26bccb2f31e8"),
                            Rate = 0.060154017728358267,
                            ReviewsCount = 1539211074L,
                            RoomsCount = 4
                        },
                        new
                        {
                            Id = new Guid("0b0d3208-237c-4958-8989-34c1ea298db6"),
                            Address = "8441 Schiller Crescent, Einarberg, Saudi Arabia",
                            BedsCount = 5,
                            CapacitySquare = 79.982866131223389,
                            GuestsCount = 7,
                            Name = "೚뿉잪篛孝齦ㄶ吊烍�",
                            OwnerId = new Guid("0024520e-9781-4fad-8248-9ffe017ac4d1"),
                            Rate = 0.71925656716514141,
                            ReviewsCount = 798476779L,
                            RoomsCount = 4
                        },
                        new
                        {
                            Id = new Guid("fa520528-3781-4e61-be39-a600bcb5dd13"),
                            Address = "5550 Schultz Shoal, South Kristin, Jamaica",
                            BedsCount = 4,
                            CapacitySquare = 14.026923264678004,
                            GuestsCount = 1,
                            Name = "럹譃돯断ࣆ머顅",
                            OwnerId = new Guid("0024520e-9781-4fad-8248-9ffe017ac4d1"),
                            Rate = 0.88675543034703075,
                            ReviewsCount = 996612426L,
                            RoomsCount = 1
                        },
                        new
                        {
                            Id = new Guid("4a098679-9acf-4849-8837-a20c6a42bad0"),
                            Address = "39639 Crist Plains, Thadfort, Tanzania",
                            BedsCount = 7,
                            CapacitySquare = 85.695926116362315,
                            GuestsCount = 7,
                            Name = "慾耠㴅翙鉪勖弛한⮎뿙",
                            OwnerId = new Guid("ff49bb87-b0cc-4fea-91e2-24d0aedfb4bc"),
                            Rate = 0.49368434952338625,
                            ReviewsCount = 387162089L,
                            RoomsCount = 2
                        },
                        new
                        {
                            Id = new Guid("fd968687-a318-4d38-a5fd-92eb23acf0f6"),
                            Address = "04975 Legros Mews, North Ciaramouth, Namibia",
                            BedsCount = 4,
                            CapacitySquare = 70.460020867726101,
                            GuestsCount = 3,
                            Name = "䩭⮇烇�Ƞ�☰턏郼",
                            OwnerId = new Guid("ff49bb87-b0cc-4fea-91e2-24d0aedfb4bc"),
                            Rate = 0.14495771218798181,
                            ReviewsCount = 640144442L,
                            RoomsCount = 2
                        },
                        new
                        {
                            Id = new Guid("a89f6840-ecb1-4470-924c-0ddf3cf3636b"),
                            Address = "720 Shayne Squares, South Lisette, Swaziland",
                            BedsCount = 3,
                            CapacitySquare = 75.868508992157743,
                            GuestsCount = 3,
                            Name = "ᇶ澕쏌薄噞汞ꂜ䤊턡",
                            OwnerId = new Guid("90448a16-0f00-4fc0-bf6c-0f8e545876dc"),
                            Rate = 0.86278800714883419,
                            ReviewsCount = 1404847108L,
                            RoomsCount = 4
                        },
                        new
                        {
                            Id = new Guid("350690b0-9e86-4cb4-ba63-799ca7330719"),
                            Address = "146 Kellen Mountain, Port Ted, Pitcairn Islands",
                            BedsCount = 8,
                            CapacitySquare = 24.365707975294303,
                            GuestsCount = 11,
                            Name = "ￎ┸羏ꥭ�涅ᓲ칡㛃",
                            OwnerId = new Guid("90448a16-0f00-4fc0-bf6c-0f8e545876dc"),
                            Rate = 0.07170099805725938,
                            ReviewsCount = 782697435L,
                            RoomsCount = 1
                        },
                        new
                        {
                            Id = new Guid("da594fbb-e62a-4bd9-8140-2b7b16afd528"),
                            Address = "8383 Edwin Estates, Bartolettiburgh, Bulgaria",
                            BedsCount = 4,
                            CapacitySquare = 8.3552779825553749,
                            GuestsCount = 1,
                            Name = "˨噋呂扉✉㺪粀׮١",
                            OwnerId = new Guid("1e0ff627-aadf-4266-aa70-d930960696db"),
                            Rate = 0.1070992044864717,
                            ReviewsCount = 937056584L,
                            RoomsCount = 1
                        },
                        new
                        {
                            Id = new Guid("2c3d1dd2-c751-474e-ba5c-3081e3ba4957"),
                            Address = "158 Durgan Well, Kyleemouth, Colombia",
                            BedsCount = 7,
                            CapacitySquare = 3.5906625697719297,
                            GuestsCount = 11,
                            Name = "ꦰ횵䤆஥尥膱쎑댺㪭",
                            OwnerId = new Guid("1e0ff627-aadf-4266-aa70-d930960696db"),
                            Rate = 0.041324305236304704,
                            ReviewsCount = 19995276L,
                            RoomsCount = 1
                        },
                        new
                        {
                            Id = new Guid("054ec238-fff0-463a-8311-9b0b9324e1b0"),
                            Address = "458 Connelly Terrace, Nadermouth, Seychelles",
                            BedsCount = 6,
                            CapacitySquare = 74.93856081946528,
                            GuestsCount = 5,
                            Name = "犅溞緈䜿됀訌捻ޗᘴ䰥",
                            OwnerId = new Guid("a432befa-d141-420a-950a-8ed8df55befb"),
                            Rate = 0.80792508907260407,
                            ReviewsCount = 699528502L,
                            RoomsCount = 1
                        },
                        new
                        {
                            Id = new Guid("a2b81065-ae1f-4919-9046-185c8de9f26d"),
                            Address = "122 Boyd Ports, North Amelia, Antigua and Barbuda",
                            BedsCount = 3,
                            CapacitySquare = 40.822095068848007,
                            GuestsCount = 5,
                            Name = "飭뉓뿢춧岎ዯ䄸᧪⌍",
                            OwnerId = new Guid("a432befa-d141-420a-950a-8ed8df55befb"),
                            Rate = 0.79686464256281475,
                            ReviewsCount = 2128596321L,
                            RoomsCount = 3
                        },
                        new
                        {
                            Id = new Guid("ee556b10-d4f3-42c6-a489-cb4be972b8cd"),
                            Address = "80408 Wunsch Square, Klockostad, Argentina",
                            BedsCount = 8,
                            CapacitySquare = 83.176691735345443,
                            GuestsCount = 12,
                            Name = "칋켛࿼쾠�隌�橱౉憘",
                            OwnerId = new Guid("df8a4170-9800-4a7c-b61d-e417d97cb2c8"),
                            Rate = 0.2199155535088283,
                            ReviewsCount = 2103860387L,
                            RoomsCount = 3
                        },
                        new
                        {
                            Id = new Guid("89985a40-e9e2-40df-b976-90f0c1d4d46d"),
                            Address = "219 Joey Mall, Harbermouth, Uganda",
                            BedsCount = 4,
                            CapacitySquare = 84.965639084534232,
                            GuestsCount = 1,
                            Name = "ꖆ뛷孓猰듦䭢㗼䝀绝",
                            OwnerId = new Guid("df8a4170-9800-4a7c-b61d-e417d97cb2c8"),
                            Rate = 0.45249321890572369,
                            ReviewsCount = 994301788L,
                            RoomsCount = 4
                        },
                        new
                        {
                            Id = new Guid("bacd01f6-7e6f-46f8-9144-92374a85f7cf"),
                            Address = "098 Roselyn Track, Lake Rowenastad, Guatemala",
                            BedsCount = 6,
                            CapacitySquare = 84.90161086156796,
                            GuestsCount = 1,
                            Name = "邢冂蘙皂㻢质눈럥鰆",
                            OwnerId = new Guid("c914b7a9-4c93-4179-b5aa-98ae4e1b0271"),
                            Rate = 0.34327804074268031,
                            ReviewsCount = 1383901836L,
                            RoomsCount = 2
                        },
                        new
                        {
                            Id = new Guid("29121930-efb2-472a-97dd-28b6f365c7d0"),
                            Address = "0556 Dale Cliff, Jacobishire, Nigeria",
                            BedsCount = 2,
                            CapacitySquare = 97.055198982861683,
                            GuestsCount = 5,
                            Name = "깆ﴴਸ਼잚ꘁ蝞㤀酦받",
                            OwnerId = new Guid("c914b7a9-4c93-4179-b5aa-98ae4e1b0271"),
                            Rate = 0.29488897170200989,
                            ReviewsCount = 962002728L,
                            RoomsCount = 3
                        },
                        new
                        {
                            Id = new Guid("a7401f79-6ed1-4934-a1db-5542719a8d16"),
                            Address = "04529 Lucio Prairie, Francismouth, Ethiopia",
                            BedsCount = 1,
                            CapacitySquare = 60.750570367200631,
                            GuestsCount = 1,
                            Name = "䯫斂仾岻�᰿扨㭞",
                            OwnerId = new Guid("fc27675e-ee5d-4f0a-b79a-5a1b7c1f3d8a"),
                            Rate = 0.65649881672000399,
                            ReviewsCount = 1358213207L,
                            RoomsCount = 1
                        },
                        new
                        {
                            Id = new Guid("ade910e1-2ed7-44be-9430-53740041d43c"),
                            Address = "6577 Blanca Row, Schmelerside, Kenya",
                            BedsCount = 5,
                            CapacitySquare = 4.5790676396517576,
                            GuestsCount = 1,
                            Name = "餐惇ꕠ︨᧡�岹쵄靃",
                            OwnerId = new Guid("fc27675e-ee5d-4f0a-b79a-5a1b7c1f3d8a"),
                            Rate = 0.64076560253600623,
                            ReviewsCount = 490744323L,
                            RoomsCount = 2
                        });
                });

            modelBuilder.Entity("Entities.Models.Occupancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EvictionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccupancyDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReservedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ReservedById");

                    b.ToTable("Occupancies");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89f2b834-6d07-488b-bb97-e9debebb6f86"),
                            Name = "Ernestine",
                            PhoneNumber = "951.477.5999 x341"
                        },
                        new
                        {
                            Id = new Guid("2d467980-ff3d-4572-b126-26bccb2f31e8"),
                            Name = "Halie",
                            PhoneNumber = "(761) 809-0397 x2076"
                        },
                        new
                        {
                            Id = new Guid("0024520e-9781-4fad-8248-9ffe017ac4d1"),
                            Name = "Hubert",
                            PhoneNumber = "550.379.2140 x3192"
                        },
                        new
                        {
                            Id = new Guid("ff49bb87-b0cc-4fea-91e2-24d0aedfb4bc"),
                            Name = "Arvid",
                            PhoneNumber = "385.608.5588 x1476"
                        },
                        new
                        {
                            Id = new Guid("90448a16-0f00-4fc0-bf6c-0f8e545876dc"),
                            Name = "Devyn",
                            PhoneNumber = "(424) 495-2883"
                        },
                        new
                        {
                            Id = new Guid("1e0ff627-aadf-4266-aa70-d930960696db"),
                            Name = "Ruby",
                            PhoneNumber = "1-338-801-6652"
                        },
                        new
                        {
                            Id = new Guid("a432befa-d141-420a-950a-8ed8df55befb"),
                            Name = "Rashawn",
                            PhoneNumber = "(347) 351-0621 x7977"
                        },
                        new
                        {
                            Id = new Guid("df8a4170-9800-4a7c-b61d-e417d97cb2c8"),
                            Name = "Brendon",
                            PhoneNumber = "(900) 689-8731 x603"
                        },
                        new
                        {
                            Id = new Guid("c914b7a9-4c93-4179-b5aa-98ae4e1b0271"),
                            Name = "Judd",
                            PhoneNumber = "739.621.9623 x569"
                        },
                        new
                        {
                            Id = new Guid("fc27675e-ee5d-4f0a-b79a-5a1b7c1f3d8a"),
                            Name = "Brandyn",
                            PhoneNumber = "723.956.9175 x0916"
                        });
                });

            modelBuilder.Entity("Entities.ReservationDate", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExtraCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("OccupancyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReservedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Date");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("OccupancyId");

                    b.HasIndex("ReservedById");

                    b.ToTable("ReservationDates");
                });

            modelBuilder.Entity("Entities.Models.Apartment", b =>
                {
                    b.HasOne("Entities.Models.User", "Owner")
                        .WithMany("Apartments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Entities.Models.Occupancy", b =>
                {
                    b.HasOne("Entities.Models.Apartment", "Apartment")
                        .WithMany("Occupancies")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "ReservedBy")
                        .WithMany("Occupancies")
                        .HasForeignKey("ReservedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("ReservedBy");
                });

            modelBuilder.Entity("Entities.ReservationDate", b =>
                {
                    b.HasOne("Entities.Models.Apartment", "Apartment")
                        .WithMany("ReservationDates")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Occupancy", "Occupancy")
                        .WithMany("ReservedDates")
                        .HasForeignKey("OccupancyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Entities.Models.User", "ReservedBy")
                        .WithMany()
                        .HasForeignKey("ReservedById");

                    b.Navigation("Apartment");

                    b.Navigation("Occupancy");

                    b.Navigation("ReservedBy");
                });

            modelBuilder.Entity("Entities.Models.Apartment", b =>
                {
                    b.Navigation("Occupancies");

                    b.Navigation("ReservationDates");
                });

            modelBuilder.Entity("Entities.Models.Occupancy", b =>
                {
                    b.Navigation("ReservedDates");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Occupancies");
                });
#pragma warning restore 612, 618
        }
    }
}
